{
    "name": "Odoo Cheque Features",
    "summary": """""",
    "description": """""",
    "author": "Indexa",
    "category": "Accounting/Accounting",
    "version": "15.0.0.0.0",
    "depends": ["odoo_cheque_management"],
    "data": [
        "data/ir_module_category_data.xml",
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "views/account_invoice_inherit_view.xml",
        "views/issued_cheque_views.xml",
        "views/bank_cheque_views.xml",
        "views/cheque_report.xml",
        "wizard/invoice_print_cheque_transient.xml",
    ],
    "installable": True,
}
