# -*- coding: utf-8 -*-
# License LGPL-3.0 or later (https://opensource.org/licenses/LGPL-3.0).
#
# This software and associated files (the "Software") may only be used (executed,
# modified, executed after modifications) if you have purchased a valid license
# from the authors, typically via Odoo Apps, or if you have received a written
# agreement from the authors of the Software (see the COPYRIGHT section below).
#
# You may develop Odoo modules that use the Software as a library (typically
# by depending on it, importing it and using its resources), but without copying
# any source code or material from the Software. You may distribute those
# modules under the license of your choice, provided that this license is
# compatible with the terms of the Odoo Proprietary License (For example:
# LGPL, MIT, or proprietary licenses similar to this one).
#
# It is forbidden to publish, distribute, sublicense, or sell copies of the Software
# or modified copies of the Software.
#
# The above copyright notice and this permission notice must be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
#########COPYRIGHT#####
# © 2017 Bernard K Too<bernard.too@optima.co.ke>
from num2words import num2words
from odoo import _, api, fields, models


class InvoiceTemplates(models.Model):
    _inherit = ["account.move"]

    @api.onchange('partner_id')
    def onchange_partner_style(self):
        self.style = self.partner_id.style or self.env.user.company_id.df_style or self.env.ref(
            'isjo_professional_templates.df_style_for_all_reports')

    @api.model
    def create(self, vals):
        res = super(InvoiceTemplates, self).create(vals)
        if res:  # trigger onchage after creating invoice to update the partner style
            res.onchange_partner_style()
        return res

    style = fields.Many2one(
        'report.template.settings',
        'Invoice Style',
        help="Select style to use when printing this invoice",
        default=lambda self: self.partner_id.style or self.env.user.company_id.
        df_style)
    project_title = fields.Char(
        'Title',
        help=
        "The title of your customer project or work you are doing for your customer"
    )
    amount_words = fields.Char(
        'Amount in Words:',
        help=
        "The invoice total amount in words is automatically generated by the system..few languages are supported currently",
        compute='_compute_num2words')

    fiscal_sequence_expiration = fields.Date(
        string='Fecha de Expiración de Secuencia Fiscal',
        compute='_compute_fiscal_sequence_expiration',
        store=False,
        help="Fecha de expiración de la secuencia fiscal activa asociada al tipo de factura"
    )

    @api.depends('name', 'ref')
    def _compute_fiscal_sequence_expiration(self):
        has_fiscal_type = 'fiscal_type_id' in self.env['account.move']._fields
        has_fiscal_seq = 'account.fiscal.sequence' in self.env
        for move in self:
            expiration_date = False
            if has_fiscal_type and has_fiscal_seq:
                fiscal_type = getattr(move, 'fiscal_type_id', False)
                if fiscal_type:
                    fiscal_sequence = self.env['account.fiscal.sequence'].search([
                        ('fiscal_type_id', '=', fiscal_type.id),
                        ('state', '=', 'active')
                    ], limit=1)
                    if fiscal_sequence:
                        expiration_date = fiscal_sequence.expiration_date
            move.fiscal_sequence_expiration = expiration_date

    def _compute_num2words(self):
        for rec in self:
            style = rec.style or rec.partner_id.style or rec.env.user.company_id.df_style or rec.env.ref(
                'isjo_professional_templates.df_style_for_all_reports')
            if style and style.aiw_report:
                try:
                    rec.amount_words = num2words(
                        rec.amount_total, lang=rec.partner_id.lang or 'en').upper()
                except NotImplementedError:
                    rec.amount_words = num2words(rec.amount_total,
                                                 lang='en').upper()
            else:
                rec.amount_words = _('DISABLED')
